### ISSUE TITLE
Sorting in ranking view does not work properly

### ISSUE THREAD

**Issue by michalkoza** [TeoTN/TFoosball#22]
It seems players are sorted by EXP in the first place even when different column is selected, so sorting only affects players with equal EXP

![tfoosball](https://cloud.githubusercontent.com/assets/2995498/25422137/1ba801ae-2a60-11e7-970d-45c705e42a0d.png)

**Comment by TeoTN** [comment]
Thanks for the report, I have confirmed the bug and the fix was released to the deployment server.
