### ISSUE TITLE
Cannnot delete matches

### ISSUE THREAD

**Issue by michalkoza** [TeoTN/TFoosball#27]
Hello Piotr,
I'm not able to remove a match.
In Matches view there is no transh icon
![tfoosball](https://user-images.githubusercontent.com/2995498/31328046-2ea325c2-acd3-11e7-983d-91b80785314c.png)

In Matches in my profile I see the icon but seems I lost permissions recently. Others could not delete it too.
![tfoosball](https://user-images.githubusercontent.com/2995498/31328100-7835a142-acd3-11e7-913a-aecebf8d0b22.png)

Cheers!

**Comment by TeoTN** [comment]
For the Profile > Matches issue should be solved now!
Regarding Matches view, I'll follow this up soon

**Comment by michalkoza** [comment]
Ok, I managed to delete a match thanks!

**Comment by TeoTN** [comment]
Solved in 2.3.0
