### ISSUE TITLE
Inconsistency in streaks for some players

### ISSUE THREAD

**Issue by michalkoza** [TeoTN/TFoosball#28]
E.g. For Maciek we have
![tfoosball](https://user-images.githubusercontent.com/2995498/31426334-36c188ac-ae63-11e7-9a88-8a09b31b37b4.png)
![tfoosball 1](https://user-images.githubusercontent.com/2995498/31426336-36e472e0-ae63-11e7-94b4-172f64913d04.png)

**Comment by michalkoza** [comment]
Leaving Brighdol team fixed the issue for Maciek

**Comment by TeoTN** [comment]
Could you please verify if the problem persists now for anyone else?
I have noticed that he has indeed left RKS Brajdol (and caused cascade delete of his matches) which was quite a disruptive action for the legacy team data. The open question is though whether you would like me to merge RKS Brajdol old ranking with the current one? I'd be more than happy to get some polling results on this matter ;)

**Comment by michalkoza** [comment]
You need to reach to the team for this on random. I'm not BIT member anymore.
But I guess we are not much interested in Brajdol results anymore.... :) I would just drop it

**Comment by TeoTN** [comment]
That was surprising answer, I'll ask them :)
